
name: Build Paper
on: [workflow_dispatch, repository_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2
              with:
                repository: PaperMC/Paper
                path: .
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache gradle
              uses: actions/cache@v2
              with:
                  path: |
                    ~/.gradle/caches
                    ~/.gradle/jdks
                    ~/.gradle/native
                    ~/.gradle/wrapper
                  key: ${{ runner.os }}-paper-2-${{ hashFiles('**/*.gradle*', 'gradle/**', 'gradle.properties') }}
                  restore-keys: ${{ runner.os }}-paper-2
                  
            - name: Change Files
              run: |
                    rm patches/server/0123-Properly-fix-item-duplication-bug.patch
                    rm patches/server/0345-Fix-MC-161754.patch
                    rm patches/server/0424-Fix-numerous-item-duplication-issues-and-teleport-is.patch
                    rm patches/server/0556-Expose-world-spawn-angle.patch
                    rm patches/server/0578-Fix-harming-potion-dupe.patch
                    rm patches/server/0715-Fix-PlayerDropItemEvent-using-wrong-item.patch

            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew paperclipJar --stacktrace
            - name: Upload
              uses: actions/upload-artifact@v2.2.4
              with:
                  path: build/libs/*
