
name: Build Paper
on: [workflow_dispatch, repository_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2
              with:
                repository: PaperMC/Paper
                path: .
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache gradle
              uses: actions/cache@v2
              with:
                  path: |
                    ~/.gradle/caches
                    ~/.gradle/jdks
                    ~/.gradle/native
                    ~/.gradle/wrapper
                  key: ${{ runner.os }}-paper-2-${{ hashFiles('**/*.gradle*', 'gradle/**', 'gradle.properties') }}
                  restore-keys: ${{ runner.os }}-paper-2
                  
            - name: Change Files
              run: |
                   ./updatePatches.sh
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew paperclipJar --stacktrace
            - name: Upload
              uses: actions/upload-artifact@v2.2.4
              with:
                  path: build/libs/*
